# Generated by Django 3.1.7 on 2021-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Oczekiwanie na dostawe'), ('2', 'W magazynie'), ('3', 'Wydano')], default='created', max_length=1),
        ),
    ]
