# Generated by Django 3.1.7 on 2021-04-13 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210409_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting for delivery'), ('2', 'In warehouse'), ('3', 'Issued')], default='created', max_length=1),
        ),
    ]
